boke1/App/views.py
from datetime import datetime

from flask import Blueprint, render_template, request, session, redirect, url_for
from App.models import *

blue = Blueprint('blue', __name__)


# 首页
@blue.route('/')
def index():
    articles = Article.query.all()
    classifies = Classify.query.all()
    return render_template('home/index.html',articles=articles,classifies=classifies)

@blue.route('/share/')
def share():
    return render_template('home/share.html')

@blue.route('/list/')
def list():
    return render_template('home/list.html')

@blue.route('/about/')
def about():
    return render_template('home/about.html')

@blue.route('/gbook/')
def gbook():
    return render_template('home/gbook.html')

@blue.route('/info/')
def info():
    return render_template('home/info.html')

@blue.route('/infopic/<id>/',methods=['POST','GET'])
def infopic(id):
    if request.method == 'POST':
        content = request.form.get('content')
        date = datetime.now().strftime('%Y-%m-%d %X')
        press = Mypress()
        press.content = content
        press.date = date
        press.articles = id
        article = Article.query.get(id)
        article.press += 1
        my_add(press)
        article = Article.query.get(id)
        mypress = Mypress.query.filter_by(articles=id)
        return render_template('home/infopic.html', article=article,mypress=mypress)
    article = Article.query.get(id)
    mypress = Mypress.query.filter_by(articles=id)

    if article:
        return render_template('home/infopic.html',article=article,mypress=mypress)
    else:
        return redirect(url_for('blue.index'))

@blue.route('/classify/<id>/')
def classify(id):
    classify = Classify.query.get(id)
    articles = classify.articles
    classifies = Classify.query.all()
    return render_template('home/index.html',articles=articles,classifies=classifies)


#后台
@blue.route('/admin/login/',methods=['POST','GET'])
def admin_login():
    if request.method == "POST":
        username = request.form.get('username')
        userwd = request.form.get('userwd')
        user = User.query.filter_by(name=username).first()
        if user:
            if userwd == user.passwd:
                session['username'] = user.name
                return render_template('admin/index.html', username=username)
            else:
                return "密码错误"
        else:
            return "用户不存在"
    return render_template('admin/login.html')

@blue.route('/admin/logout/')
def admin_logout():
    session.pop('username')
    return redirect(url_for('blue.admin_login'))

@blue.route('/admin/index/')
def admin_index():
    username = session.get('username','')
    return render_template('admin/index.html',username=username)

@blue.route('/admin/article/',methods=['POST',"GET"])
def admin_article():
    username = session.get('username','')
    articles = Article.query.all()
    return render_template('admin/article.html',articles=articles,username=username)

@blue.route('/admin/notice/')
def admin_notice():
    username = session.get('username','')
    return render_template('admin/notice.html',username=username)

@blue.route('/admin/comment/')
def admin_comment():
    username = session.get('username','')
    mypress = Mypress.query.all()
    return render_template('admin/comment.html',username=username,mypress=mypress)

@blue.route('/admin/category/')
def admin_category():
    username = session.get('username','')
    classifies = Classify.query.all()
    return render_template('admin/category.html',username=username,classifies=classifies)

@blue.route('/admin/flink/')
def admin_flink():
    username = session.get('username','')
    render_template('admin/flink.html',username=username)

@blue.route('/admin/manage-user/')
def admin_manage_user():
    username = session.get('username','')
    return render_template('admin/manage-user.html',username=username)

@blue.route('/admin/loginlog/')
def admin_loginlog():
    username = session.get('username','')
    return render_template('admin/loginlog.html',username=username)

@blue.route('/admin/setting/')
def admin_setting():
    username = session.get('username','')
    return render_template('admin/setting.html',username=username)

@blue.route('/admin/readset/')
def admin_readset():
    username = session.get('username','')
    return render_template('admin/readset.html',username=username)

@blue.route('/admin/add-notice/')
def admin_add_notice():
    username = session.get('username','0')
    return render_template('admin/add-notice.html',username=username)

@blue.route('/admin/update-article/<id>/',methods=['POST',"GET"])
def admin_update_article(id):
    username = session.get('username','')
    if request.method == 'POST':
        title = request.form.get('title')
        context = request.form.get('context')
        tag = request.form.get('tag')
        classify = request.form.get('classify')
        date = datetime.now().strftime('%Y-%m-%d %X')
        article = Article.query.get(id)
        article.context = context
        article.title = title
        article.tag = tag
        article.date = date
        print(classify)
        classify = Classify.query.filter_by(name=classify).first()
        if article.myclassify != classify.id:
            print(article.myclassify, classify.id)
            article.myclassify = classify.id
            # print(classify.mycount)
            classify.mycount += int(1)
            # print(classify.mycount)
            # print(Classify.query.get(article.myclassify).mycount)
            Classify.query.get(article.myclassify).mycount -= int(1)
            # print(Classify.query.get(article.myclassify).mycount)
            my_update()
            return redirect(url_for('blue.admin_article', values='修改成功'))
        else:
            my_update()
            return redirect(url_for('blue.admin_article', values='修改成功'))
    article = Article.query.get(id)
    classifies = Classify.query.all()
    return render_template('admin/modify_article.html', article=article, classifies=classifies, username=username)

@blue.route('/admin/update-category/<id>/',methods=['POST',"GET"])
def admin_update_category(id):
    username = session.get('username','')
    if request.method=="POST":
        name = request.form.get('name')
        another_name = request.form.get('another_name')
        classify = Classify.query.get(id)
        classify.name=name
        classify.another_name=another_name
        my_update()
        return redirect(url_for('blue.admin_category',username=username))
    classify = Classify.query.get(id)
    return render_template('admin/update-category.html',username=username,classify=classify)


@blue.route('/admin/update-flink')
def admin_update_flink():
    username = session.get('username','0')
    return render_template('admin/update-flink.html',username=username)

@blue.route('/admin/add-flink/')
def admin_add_flink():
    username = session.get('username','0')
    return render_template('admin/add-flink.html',username=username)


@blue.route('/delete_classify/<id>/')
def delete_classify(id):
    classify=Classify.query.filter_by(id=id).first()
    my_delete(classify)
    return redirect(url_for('blue.admin_category'))

@blue.route('/delete_article/<id>/')
def delete_article(id):
    article=Article.query.filter_by(id=id).first()
    if article.myclassify :
        classify = Classify.query.get(article.myclassify)
        classify.mycount -= int(1)
    my_delete(article)
    return redirect(url_for('blue.admin_article'))

@blue.route('/delete_press/<id>/',methods=['POST','GET'])
def admin_delete_press(id):
    username = session.get('username','')
    print('ok:',id)
    press=Mypress.query.filter_by(id=id).first()
    my_delete(press)
    mypress = Mypress.query.all()
    return redirect(url_for('blue.admin_comment',mypress=mypress,username=username))

@blue.route('/add_category/',methods=['POST','GET'])
def add_category():
    username = session.get('username', '')
    if request.method == 'POST':
        name = request.form.get('name')
        another_name = request.form.get('another_name')
        classify = Classify()
        classify.name=name
        classify.another_name=another_name
        my_add(classify)
        return redirect(url_for('blue.admin_category'))
    classifies = Classify.query.all()
    return render_template('admin/category.html', username=username, classifies=classifies)


@blue.route('/admin/add-article/',methods=['POST','GET'])
def admin_add_article():
    username = session.get('username','')
    if request.method == 'POST':
        context = request.form.get('context')
        title = request.form.get('title')
        tag = request.form.get('tag')
        classify = request.form.get('classify')
        date = datetime.now().strftime('%Y-%m-%d %X')
        if classify != None :
            classify = Classify.query.filter_by(name=classify).first()
            # print(context,tag,title,category)
            # classify = Classify.query.filter_by(id=category).first()
            classify.mycount += int(1)
            article = Article(title=title, context=context, date=date, myclassify=classify.id, tag=tag)
            my_add(article)
            return redirect(url_for('blue.admin_article'))
        article = Article(title=title,context=context,date=date,tag=tag)
        my_add(article)
        return redirect(url_for('blue.admin_article'))
    else:
        classifies = Classify.query.all()
        if classifies:
            return render_template('admin/add-article.html',username=username,classifies=classifies)
        else:
            return redirect(url_for('blue.admin_category'))

@blue.route('/check_press/<id>/',methods=['POST','GET'])
def admin_check_press(id):
    username = session.get('username', '')
    if username:
        acticle = Article.query.get(id)
        mypress = acticle.my_press
        print(mypress)
        return render_template('admin/mypress.html',mypress=mypress)
    else:

boke1/App/templates/home/index.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>首页_个人博客网站</title>
<meta name="keywords" content="个人博客,娜姐个人博客,个人博客模板,娜姐" />
<meta name="description" content="娜姐个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/static/home/css/base.css" rel="stylesheet">
<link href="/static/home/css/index.css" rel="stylesheet">
<link href="/static/home/css/m.css" rel="stylesheet">
<script src="/static/home/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/home/js/comm.js"></script>
<!--[if lt IE 9]>
<script src="/static/home/js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">娜姐个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="{{ url_for('blue.index') }}">网站首页</a></li>
      <li><a href="{{ url_for('blue.share') }}">我的相册</a></li>
      <li><a href="{{ url_for('blue.list') }}">我的日记</a></li>
      <li><a href="{{ url_for('blue.about') }}">关于我</a></li>
      <li><a href="{{ url_for('blue.gbook') }}">留言</a></li>
      <li><a href="{{ url_for('blue.info') }}">内容页</a></li>
      <li><a href="#">内容页</a></li>
    </ul>
</nav>
</header>
<article>
  <aside class="l_box">
      <div class="about_me">
        <h2>关于我</h2>
        <ul>
          <i><img src="/static/home/images/4.jpg"></i>
          <p><b>summer</b>，一个90后草根女站长！19年入行。一直潜心研究python端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
        </ul>
      </div>
      <div class="wdxc">
        <h2>我的相册</h2>
        <ul>
          <li><a href="/"><img src="/static/home/images/7.jpg"></a></li>
          <li><a href="/"><img src="/static/home/images/8.jpg"></a></li>
          <li><a href="/"><img src="/static/home/images/9.jpg"></a></li>
          <li><a href="/"><img src="/static/home/images/10.jpg"></a></li>
          <li><a href="/"><img src="/static/home/images/11.jpg"></a></li>
          <li><a href="/"><img src="/static/home/images/12.jpg"></a></li>
        </ul>
      </div>
      <div class="search">
        <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
          <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
          <input name="show" value="title" type="hidden">
          <input name="tempid" value="1" type="hidden">
          <input name="tbname" value="news" type="hidden">
          <input name="Submit" class="input_submit" value="搜索" type="submit">
        </form>
      </div>
      <div class="fenlei">
        <h2>文章分类</h2>
        <ul>
            {% for classify in classifies %}
                <li>
                    <a href="{{ url_for('blue.classify',id=classify.id) }}">{{ classify.name }}</a>
                    <a href="{{ url_for('blue.classify',id=classify.id) }}">({{ classify.mycount }})</a>
                </li>
            {% endfor %}
        </ul>
      </div>
       <div class="tuijian">
        <h2>站长推荐</h2>
        <ul>
          <li><a href="/">你是什么人便会遇上什么人</a></li>
          <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
          <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
          <li><a href="/">个人博客模板《绅士》后台管理</a></li>
          <li><a href="/">你是什么人便会遇上什么人</a></li>
          <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
          <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
          <li><a href="/">个人博客模板《绅士》后台管理</a></li>
        </ul>
      </div>
      <div class="links">
        <h2>友情链接</h2>
        <ul>
          <a href="http://www.yangqq.com">个人博客</a> <a href="http://www.yangqq.com">娜姐博客</a>
        </ul>
      </div>
      <div class="guanzhu">
        <h2>关注我 么么哒</h2>
        <ul>
          <img src="/static/home/images/wx.jpg">
        </ul>
      </div>
  </aside>
  <main class="r_box">
    <ul>
        {% for article in articles %}
            <li><i><a href="/"><img src="/static/home/images/1.jpg"></a></i>
                <h3><a href="{{ url_for('blue.infopic',id=article.id)}}">{{ article.title }}</a></h3>
                {{ article.context }}
             </li>
        {% endfor %}
    </ul>
  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>

boke1/App/templates/home/infopic.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>首页_杨青个人博客 - 一个站在web前端设计之路的女技术员个人博客网站</title>
<meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青" />
<meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/static/home/css/base.css" rel="stylesheet">
<link href="/static/home/css/index.css" rel="stylesheet">
<link href="/static/home/css/infopic.css" rel="stylesheet">
<link href="/static/home/css/m.css" rel="stylesheet">
<script src="/static/home/js/jquery.min.js" type="text/javascript"></script>
<script src="/static/home/js/piccontent.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/home/js/hc-sticky.js"></script>
<script type="text/javascript" src="/static/home/js/comm.js"></script>
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">杨青个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="{{ url_for('blue.index') }}">网站首页</a></li>
      <li><a href="{{ url_for('blue.share') }}">我的相册</a></li>
      <li><a href="{{ url_for('blue.list') }}">我的日记</a></li>
      <li><a href="{{ url_for('blue.about') }}">关于我</a></li>
      <li><a href="{{ url_for('blue.gbook') }}">留言</a></li>
      <li><a href="{{ url_for('blue.info') }}">内容页</a></li>
      <li><a href="#">内容页</a></li>
    </ul>
</nav>
</header>
<article>
  <aside class="l_box">
    <div class="about_me">
      <h2>关于我</h2>
      <ul>
        <i><img src="/static/home/images/4.jpg"></i>
        <p><b>杨青</b>，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
      </ul>
    </div>
    <div class="wdxc">
      <h2>我的相册</h2>
      <ul>
        <li><a href="/"><img src="/static/home/images/7.jpg"></a></li>
        <li><a href="/"><img src="/static/home/images/8.jpg"></a></li>
        <li><a href="/"><img src="/static/home/images/9.jpg"></a></li>
        <li><a href="/"><img src="/static/home/images/10.jpg"></a></li>
        <li><a href="/"><img src="/static/home/images/11.jpg"></a></li>
        <li><a href="/"><img src="/static/home/images/12.jpg"></a></li>
      </ul>
    </div>
     <div class="search">
      <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>
    <div class="fenlei">
      <h2>文章分类</h2>
      <<ul>
            {% for classify in classifies %}
                <li>
                    <a href="{{ url_for('blue.classify',id=classify.id) }}">{{ classify.name }}</a>
                    <a href="#">({{ classify.count }})</a>
                </li>
            {% endfor %}
        </ul>
    </div>

    <div class="guanzhu">
      <h2>关注我 么么哒</h2>
      <ul>
        <img src="/static/home/images/wx.jpg">
      </ul>
    </div>
  </aside>
  <main>
  <div class="picsbox">
    <div class="bodymodal"></div>
    <!--播放到第一张图的提示-->
    <div class="firsttop">
      <div class="firsttop_right">
        <div class="close2"> <a class="closebtn1" title="关闭" href="javascript:void(0)"></a> </div>
        <div class="replay">
          <h2 id="div-end-h2"> 已到第一张图片了。 </h2>
          <p> <a class="replaybtn1" href="javascript:;">重新播放</a> </p>
        </div>
      </div>
    </div>
    <!--播放到最后一张图的提示-->
    <div class="endtop">
      <div class="firsttop_right">
        <div class="close2"> <a class="closebtn2" title="关闭" href="javascript:void(0)"></a> </div>
        <div class="replay">
          <h2 id="H1"> 已到最后一张图片了。 </h2>
          <p> <a class="replaybtn2" href="javascript:;">重新播放</a> </p>
        </div>
      </div>
    </div>
    <!--弹出层结束-->
    <!--图片特效内容开始-->
    <div class="piccontext">
      <h2> {{ article.title }}</h2>
      <div class="source">
        <div class="source_left"><span>{{ article.date }}</span> </div>
        <div class="source_right"> <a href="javascript:;" class="list">列表查看</a> </div>
        <div class="source_right1"> <a href="javascript:;" class="gaoqing">高清查看</a> </div>
      </div>
      <!--大图展示-->
      <div class="picshow">
        <div class="picshowtop"> <a href="#"><img src="" alt="" id="pic1" curindex="0" /></a> <a id="preArrow" href="javascript:void(0)" class="contextDiv" title="上一张"><span id="preArrow_A"></span></a> <a id="nextArrow" href="javascript:void(0)" class="contextDiv" title="下一张"><span id="nextArrow_A"></span></a> </div>
        <div class="picshowtxt">
          <div class="picshowtxt_left"><span>1</span>/<i>12</i></div>
          <div class="picshowtxt_right"></div>
        </div>
        <div class="picshowlist">
          <div class="picshowlist_mid">
            <div class="picmidleft"> <a href="javascript:void(0)" id="preArrow_B"><span class="sleft"></span></a> </div>
            <div class="picmidmid">
              <ul>
                <li> <a href="javascript:void(0);"><img src="/static/home/images/1.jpg" alt="" bigimg="images/1.jpg" text="《古剑》小师妹迪丽热巴清新写真宛若小仙女" /></a></li>
                <li> <a href="javascript:void(0);"><img src="/static/home/images/2.jpg" alt="" bigimg="images/2.jpg" text="《古剑》小师妹迪丽热巴清新写真宛若小仙女" /></a></li>
                <li> <a href="javascript:void(0);"><img src="/static/home/images/3.jpg" alt="" bigimg="images/3.jpg" text="《古剑》小师妹迪丽热巴清新写真宛若小仙女" /></a></li>
                <li> <a href="javascript:void(0);"><img src="/static/home/images/4.jpg" alt="" bigimg="images/4.jpg" text="《古剑》小师妹迪丽热巴清新写真宛若小仙女" /></a></li>
                <li> <a href="javascript:void(0);"><img src="/static/home/images/5.jpg" alt="" bigimg="images/5.jpg" text="《古剑》小师妹迪丽热巴清新写真宛若小仙女" /></a></li>
                <li> <a href="javascript:void(0);"><img src="/static/home/images/6.jpg" alt="" bigimg="images/6.jpg" text="《古剑》小师妹迪丽热巴清新写真宛若小仙女" /></a></li>
                <li> <a href="javascript:void(0);"><img src="/static/home/images/7.jpg" alt="" bigimg="images/7.jpg" text="《古剑》小师妹迪丽热巴清新写真宛若小仙女" /></a></li>
                <li> <a href="javascript:void(0);"><img src="/static/home/images/8.jpg" alt="" bigimg="images/8.jpg" text="《古剑》小师妹迪丽热巴清新写真宛若小仙女" /></a></li>
                <li> <a href="javascript:void(0);"><img src="/static/home/images/9.jpg" alt="" bigimg="images/9.jpg" text="《古剑》小师妹迪丽热巴清新写真宛若小仙女" /></a></li>
                <li> <a href="javascript:void(0);"><img src="/static/home/images/10.jpg" alt="" bigimg="images/10.jpg" text="《古剑》小师妹迪丽热巴清新写真宛若小仙女" /></a></li>
                <li> <a href="javascript:void(0);"><img src="/static/home/images/11.jpg" alt="" bigimg="images/11.jpg" text="《古剑》小师妹迪丽热巴清新写真宛若小仙女" /></a></li>
                <li> <a href="javascript:void(0);"><img src="/static/home/images/12.jpg" alt="" bigimg="images/12.jpg" text="《古剑》小师妹迪丽热巴清新写真宛若小仙女" /></a></li>
              </ul>
            </div>
            <div class="picmidright"> <a href="javascript:void(0)" id="nextArrow_B"><span class="sright"></span></a> </div>
          </div>
        </div>
      </div>

      <!--列表展示-->
      <div class="piclistshow">
        <ul>
          <li>
            <div class="picimg"><img src="/static/home/images/1.jpg" alt="" /></div>
            <div class="pictxt">
              <h3>《古剑》小师妹迪丽热巴清新写真宛若小仙女<span>(1/12)</span></h3>
            </div>
          </li>
          <li>
            <div class="picimg"><img src="/static/home/images/2.jpg" alt="" /></div>
            <div class="pictxt">
              <h3>《古剑》小师妹迪丽热巴清新写真宛若小仙女<span>(2/12)</span></h3>
            </div>
          </li>
          <li>
            <div class="picimg"><img src="/static/home/images/3.jpg" alt="" /></div>
            <div class="pictxt">
              <h3>《古剑》小师妹迪丽热巴清新写真宛若小仙女<span>(3/12)</span></h3>
            </div>
          </li>
          <li>
            <div class="picimg"><img src="/static/home/images/4.jpg" alt="" /></div>
            <div class="pictxt">
              <h3>《古剑》小师妹迪丽热巴清新写真宛若小仙女<span>(4/12)</span></h3>
            </div>
          </li>
          <li>
            <div class="picimg"><img src="/static/home/images/5.jpg" alt="" /></div>
            <div class="pictxt">
              <h3>《古剑》小师妹迪丽热巴清新写真宛若小仙女<span>(5/12)</span></h3>
            </div>
          </li>
          <li>
            <div class="picimg"><img src="/static/home/images/6.jpg" alt="" /></div>
            <div class="pictxt">
              <h3>《古剑》小师妹迪丽热巴清新写真宛若小仙女<span>(6/12)</span></h3>
            </div>
          </li>
          <li>
            <div class="picimg"><img src="/static/home/images/7.jpg" alt="" /></div>
            <div class="pictxt">
              <h3>《古剑》小师妹迪丽热巴清新写真宛若小仙女<span>(7/12)</span></h3>
            </div>
          </li>
          <li>
            <div class="picimg"><img src="/static/home/images/8.jpg" alt="" /></div>
            <div class="pictxt">
              <h3>《古剑》小师妹迪丽热巴清新写真宛若小仙女<span>(8/12)</span></h3>
            </div>
          </li>
          <li>
            <div class="picimg"><img src="/static/home/images/9.jpg" alt="" /></div>
            <div class="pictxt">
              <h3>《古剑》小师妹迪丽热巴清新写真宛若小仙女<span>(9/12)</span></h3>
            </div>
          </li>
          <li>
            <div class="picimg"><img src="/static/home/images/10.jpg" alt="" /></div>
            <div class="pictxt">
              <h3>《古剑》小师妹迪丽热巴清新写真宛若小仙女<span>(10/12)</span></h3>
            </div>
          </li>
          <li>
            <div class="picimg"><img src="/static/home/images/11.jpg" alt="" /></div>
            <div class="pictxt">
              <h3>《古剑》小师妹迪丽热巴清新写真宛若小仙女<span>(11/12)</span></h3>
            </div>
          </li>
          <li>
            <div class="picimg"><img src="/static/home/images/12.jpg" alt="" /></div>
            <div class="pictxt">
              <h3>《古剑》小师妹迪丽热巴清新写真宛若小仙女<span>(12/12)</span></h3>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <div class="pictext">
      <ul>
        {{ article.context }}
      </ul>
    </div>
    <div class="share">
      <p class="diggit"><a href="JavaScript:makeRequest('/e/public/digg/?classid=3&amp;id=19&amp;dotop=1&amp;doajax=1&amp;ajaxarea=diggnum','EchoReturnedText','GET','');"> 很赞哦！ </a>(<b id="diggnum"><script type="text/javascript" src="/e/public/ViewClick/?classid=2&id=20&down=5"></script>13</b>)</p>
    </div>
 <div class="nextinfo">
      <p>上一篇：<a href="/news/life/2018-03-13/804.html">作为一个设计师,如果遭到质疑你是否能恪守自己的原则?</a></p>
      <p>下一篇：<a href="/news/life/">返回列表</a></p>
    </div>
    <div class="news_pl">
        <h2>文章评论</h2>
        {% for press in mypress %}
            <div class="gbko">
              <script src="/e/pl/more/?classid=77&amp;id=106&amp;num=20"></script>
              <div class="fb">
                <ul>
                  <p class="fbtime"><span>{{ press.date }}</span>dancesmile</p>
                  <p class="fbinfo">{{ press.content }}</p>
                </ul>
              </div>
        {% endfor %}



          <script>
		  function CheckPl(obj)
		  {
		  if(obj.saytext.value=="")
		  {
		  alert("您没什么话要说吗？");
		  obj.saytext.focus();
		  return false;
		  }
		  return true;
		  }
		  </script>
          <form action="{{ url_for('blue.infopic',id=article.id) }}" method="post" name="saypl" id="saypl" onsubmit="return CheckPl(document.saypl)">
            <div id="plpost">
              <p class="saying"><span><a href="/e/pl/?classid=77&amp;id=106">共有<script type="text/javascript" src="/e/public/ViewClick/?classid=77&amp;id=106&amp;down=2"></script>{{ article.press }}条评论</a></span>来说两句吧...</p>
              <input name="nomember" type="hidden" id="nomember" value="1" checked="checked">
              <textarea name="content" rows="6" id="saytext"></textarea>
              <input name="cont" type="submit" value="提交">
              <input name="id" type="hidden" id="id" value="106">
              <input name="classid" type="hidden" id="classid" value="77">
              <input name="enews" type="hidden" id="enews" value="AddPl">
              <input name="repid" type="hidden" id="repid" value="0">
              <input type="hidden" name="ecmsfrom" value="/joke/talk/2018-07-23/106.html">
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>